import type { Category, Post, User } from './types';

export const mockUser: User = {
  id: 'usr-admin-001',
  rollNo: 'ADMIN001',
  name: 'Campus Admin',
  role: 'ADMIN',
  email: 'admin@example.edu',
  year: '2',
  branch: 'CSE',
  section: 'A',
  active: true,
};

export const mockCategories: Category[] = [
  { id: 'cat-hackathons', name: 'Hackathons', type: 'DEADLINE', sortOrder: 0 },
  { id: 'cat-announcements', name: 'Announcements', type: 'NOTICE', sortOrder: 1 },
  { id: 'cat-workshops', name: 'Workshops', type: 'DEADLINE', sortOrder: 2 },
  { id: 'cat-events', name: 'Events', type: 'DEADLINE', sortOrder: 3 },
  { id: 'cat-exampdfs', name: 'Exam PDFs', type: 'NOTICE', sortOrder: 4 },
  { id: 'cat-labdetails', name: 'Lab details', type: 'NOTICE', sortOrder: 5 },
  { id: 'cat-registrations', name: 'Other registrations', type: 'DEADLINE', sortOrder: 6 },
];

const catMap = Object.fromEntries(mockCategories.map((c) => [c.id, c]));

// ISO strings anchored around October 2026
const now = new Date();
const tonight = new Date(now.getTime() + 45 * 60 * 1000).toISOString(); // ~45 mins left
const tomorrowNoon = new Date(now.getTime() + 13 * 3600 * 1000).toISOString();
const tomorrowEve = new Date(now.getTime() + 18 * 3600 * 1000).toISOString();
const twoDaysLater = new Date(now.getTime() + 42 * 3600 * 1000).toISOString();
const threeDaysLater = new Date(now.getTime() + 66 * 3600 * 1000).toISOString();

export const mockPosts: Post[] = [
  {
    id: 'post-bts-submission',
    categoryId: 'cat-hackathons',
    type: 'DEADLINE',
    title: '🚀 Build to Ship Hackathon — Final Code & Link Submission',
    summary: 'Submit your Build to Ship Hackathon project before 11:59 PM sharp! Ensure your demo and GitHub repository links are publicly accessible.',
    source: 'Ankitha Mam Niat',
    link: 'https://challazo.nxtlab.tech/register',
    deadlineAt: tonight,
    pinned: true,
    priority: 'CRITICAL',
    status: 'ACTIVE',
    category: catMap['cat-hackathons'],
    createdAt: '2026-10-06T10:51:27.000Z',
    updatedAt: '2026-10-06T10:51:27.000Z',
  },
  {
    id: 'post-common-assessment',
    categoryId: 'cat-announcements',
    type: 'DEADLINE',
    title: '📝 University Common LMS Assessment — Problem-Solving Skills',
    summary: 'Mandatory Common Assessment for all B.Tech 2nd Year students scheduled for 7th October. Solve in any programming language of your choice. Contributes to performance leaderboard.',
    source: 'Ankitha Mam Niat',
    deadlineAt: tomorrowEve,
    pinned: true,
    priority: 'CRITICAL',
    status: 'ACTIVE',
    category: catMap['cat-announcements'],
    createdAt: '2026-10-06T08:59:55.000Z',
    updatedAt: '2026-10-06T08:59:55.000Z',
  },
  {
    id: 'post-backend-records',
    categoryId: 'cat-labdetails',
    type: 'DEADLINE',
    title: '📂 Backend Lab Records — Final Submission Deadline',
    summary: 'All students must submit their complete and properly written backend lab records by 7th October. Ensure all signatures and experiments are intact.',
    source: 'Garima Agrawal',
    deadlineAt: tomorrowEve,
    pinned: false,
    priority: 'CRITICAL',
    status: 'ACTIVE',
    category: catMap['cat-labdetails'],
    createdAt: '2026-10-05T11:08:22.000Z',
    updatedAt: '2026-10-05T11:08:22.000Z',
  },
  {
    id: 'post-bts-feedback',
    categoryId: 'cat-hackathons',
    type: 'DEADLINE',
    title: '💬 Build to Ship Hackathon — Participant Feedback Form',
    summary: 'All hackathon participants are requested to fill out the official feedback form to share their experience and help improve upcoming events.',
    source: 'Ankitha Mam Niat',
    link: 'https://forms.ccbp.in/bts-hackathon-feedback-form-mrv',
    deadlineAt: tomorrowNoon,
    pinned: false,
    priority: 'NORMAL',
    status: 'ACTIVE',
    category: catMap['cat-hackathons'],
    createdAt: '2026-10-06T10:50:50.000Z',
    updatedAt: '2026-10-06T10:50:50.000Z',
  },
  {
    id: 'post-sih-teams',
    categoryId: 'cat-hackathons',
    type: 'NOTICE',
    title: '📢 Smart India Hackathon (SIH 2026) — Final 24 Teams Community',
    summary: 'There are 52 shortlisted SIH teams, of which 24 teams are from NIAT. Shortlisted teams and members must join the official WhatsApp community immediately.',
    source: 'Ankitha Mam Niat',
    link: 'https://chat.whatsapp.com/LDOX58TIwN7Gx1p6t5uTzu',
    pinned: true,
    priority: 'CRITICAL',
    status: 'ACTIVE',
    category: catMap['cat-hackathons'],
    createdAt: '2026-09-13T04:25:18.000Z',
    updatedAt: '2026-09-13T04:25:18.000Z',
  },
  {
    id: 'post-grit-exam',
    categoryId: 'cat-registrations',
    type: 'DEADLINE',
    title: '🎯 GRIT Examination Registration — 10th October Slot Booking',
    summary: 'Register for your preferred slot (Slot 1: 9:20 AM, Slot 2: 10:50 AM, Slot 3: 1:00 PM, Slot 4: 2:30 PM). Safe Exam Browser (SEB) verification required beforehand.',
    source: 'Ankitha Mam Niat',
    deadlineAt: twoDaysLater,
    pinned: false,
    priority: 'CRITICAL',
    status: 'ACTIVE',
    category: catMap['cat-registrations'],
    createdAt: '2026-10-06T08:37:02.000Z',
    updatedAt: '2026-10-06T08:37:02.000Z',
  },
  {
    id: 'post-mid2-qb',
    categoryId: 'cat-exampdfs',
    type: 'NOTICE',
    title: '📚 B.Tech II Year Mid-2 Examinations — Question Bank & Solutions',
    summary: 'Access the master Question Bank spreadsheet with complete solutions for DAA, Digital Electronics, Probability & Statistics, and LRAS.',
    source: 'Success Coach',
    link: 'https://docs.google.com/spreadsheets/d/15v07En1OeI4tMxAO_SkVW5PIwNrdQPqTtArPOoGk9bs/edit?gid=0#gid=0',
    pinned: false,
    priority: 'NORMAL',
    status: 'ACTIVE',
    category: catMap['cat-exampdfs'],
    createdAt: '2026-09-24T04:23:05.000Z',
    updatedAt: '2026-09-24T04:23:05.000Z',
  },
  {
    id: 'post-cp-training',
    categoryId: 'cat-workshops',
    type: 'DEADLINE',
    title: '💡 Offline Competitive Programming (CP) Training Program',
    summary: 'Level up problem-solving skills for ICPC and top product companies. Fill the interest form for 1:1 mentor selection and offline onboarding.',
    source: 'Ankitha Mam Niat',
    link: 'https://docs.google.com/forms/d/e/1FAIpQLSfWePxiURp2dK_NEqpmF0pOZZhTRCh547guB_ZIVIbgOS1VEQ/viewform',
    deadlineAt: threeDaysLater,
    pinned: false,
    priority: 'NORMAL',
    status: 'ACTIVE',
    category: catMap['cat-workshops'],
    createdAt: '2026-10-06T03:59:11.000Z',
    updatedAt: '2026-10-06T03:59:11.000Z',
  },
  {
    id: 'post-mudu-login',
    categoryId: 'cat-announcements',
    type: 'NOTICE',
    title: '🔑 MUDU Student Portal Login Credentials & Guidelines',
    summary: 'Login at https://mrtc.mudu.in/login. Use your Roll Number or registered Email ID as Login ID, and your Roll Number as password.',
    source: 'Ankitha Mam Niat',
    link: 'https://mrtc.mudu.in/login',
    pinned: false,
    priority: 'NORMAL',
    status: 'ACTIVE',
    category: catMap['cat-announcements'],
    createdAt: '2026-10-06T08:08:39.000Z',
    updatedAt: '2026-10-06T08:08:39.000Z',
  },
  {
    id: 'post-qr-attendance',
    categoryId: 'cat-announcements',
    type: 'NOTICE',
    title: '📱 Mandatory QR Attendance via My NIAT App (v53)',
    summary: 'Update the My NIAT App to version 53 from the Play Store/App Store. Ensure your device UUID is linked before entering classrooms to avoid missed attendance.',
    source: 'Ankitha Mam Niat',
    pinned: false,
    priority: 'NORMAL',
    status: 'ACTIVE',
    category: catMap['cat-announcements'],
    createdAt: '2026-09-24T11:33:17.000Z',
    updatedAt: '2026-09-24T11:33:17.000Z',
  },
  {
    id: 'post-daa-manual',
    categoryId: 'cat-labdetails',
    type: 'NOTICE',
    title: '📖 DAA Lab Record — Complete All 14 Experiments',
    summary: 'For the DAA Lab Record, students are required to write all 14 experiments completely and cleanly. Strictly submit on or before the deadline.',
    source: 'Success Coach',
    pinned: false,
    priority: 'NORMAL',
    status: 'ACTIVE',
    category: catMap['cat-labdetails'],
    createdAt: '2026-09-30T09:30:17.000Z',
    updatedAt: '2026-09-30T09:30:17.000Z',
  },
  {
    id: 'post-hacktoberfest',
    categoryId: 'cat-workshops',
    type: 'NOTICE',
    title: '🌍 Hacktoberfest 2026 — Start Your Open Source Journey',
    summary: 'October is here! Explore beginner-friendly issues, create pull requests, participate in DEV challenges, and build your developer profile.',
    source: 'Success Coach',
    link: 'https://hacktoberfest.com/schedule/',
    pinned: false,
    priority: 'NORMAL',
    status: 'ACTIVE',
    category: catMap['cat-workshops'],
    createdAt: '2026-10-01T10:43:35.000Z',
    updatedAt: '2026-10-01T10:43:35.000Z',
  },
  {
    id: 'post-clutch-media',
    categoryId: 'cat-events',
    type: 'NOTICE',
    title: '🎮 CLUTCH 2026 Hyderabad Esports Tournament — Highlights & Media',
    summary: 'Event photos and tournament videos for Valorant, BGMI, and Free Fire are now available in the shared Google Drive drive.',
    source: 'Ankitha Mam Niat',
    link: 'https://drive.google.com/drive/folders/1rfL7wGWZly_Jh_fyo7jIIlDn9v0RSCpT',
    pinned: false,
    priority: 'NORMAL',
    status: 'ACTIVE',
    category: catMap['cat-events'],
    createdAt: '2026-09-28T05:26:07.000Z',
    updatedAt: '2026-09-28T05:26:07.000Z',
  },
  {
    id: 'post-internship-form',
    categoryId: 'cat-registrations',
    type: 'DEADLINE',
    title: '💼 Internship Verification — Upload Offer Letter / Certificate',
    summary: 'Students currently doing or who have completed internships must submit proof of completion or offer letter via the verification form.',
    source: 'Ankitha Mam Niat',
    link: 'https://docs.google.com/forms/d/e/1FAIpQLSfMC1nVAHkI3YgfmUKHq8E-qAqqRrQXh3z-NeYhXTa8Ms14Dw/viewform',
    deadlineAt: threeDaysLater,
    pinned: false,
    priority: 'NORMAL',
    status: 'ACTIVE',
    category: catMap['cat-registrations'],
    createdAt: '2026-10-01T05:07:58.000Z',
    updatedAt: '2026-10-01T05:07:58.000Z',
  },
];

export function getMockDashboardData() {
  const pinned = mockPosts.filter((p) => p.pinned);
  const closingSoon = mockPosts.filter(
    (p) => p.type === 'DEADLINE' && p.deadlineAt && new Date(p.deadlineAt).getTime() - Date.now() < 24 * 3600 * 1000
  );
  const pending = mockPosts.filter((p) => p.type === 'DEADLINE');
  const fresh = mockPosts.slice(0, 6);

  return {
    pinned,
    closingSoon,
    pending,
    fresh,
    categories: mockCategories,
  };
}
